version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: sidekiq-example-redis
    ports:
      - "6379:6379"
    networks:
      - sidekiq-net

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile.sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - .:/rails
    depends_on:
      - redis
    networks:
      - sidekiq-net

  mailcatcher:
    image: schickling/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"  # Porta para acessar a interface web do Mailcatcher
      - "1025:1025"  # Porta para enviar emails para o Mailcatcher
    networks:
      - sidekiq-net

networks:
  sidekiq-net:
    driver: bridge
