default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV["PG_HOST"] %>
  database: <%= ENV["PG_DATABASE"] %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  port: <%= ENV["PG_PORT"] %>

test:
  <<: *default
  database: <%= ENV["PG_DATABASE"] %>

production:
  <<: *default
  database: <%= ENV["PG_DATABASE"] %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
